### PR TITLE
Ignore GCC attributes warning

### PR DESCRIPTION
**Pull request by Randshot**

### CODE REVIEW

**Comment by JustasMasiulis** [comment]
Oh nono I meant it like this `alignas(detail::buffer_align<T>()) XORSTR_VOLATILE std::uint64_t _storage[detail::buffer_size<T>()];`  because this doesn't even compile 😄

**Comment by Randshot** [comment]
Yeah, also noticed that it doesn't compile on apple-clang for me, but GCC-8 works just fine.

**Comment by Randshot** [comment]
Here is the version output.
```
$ clang -v
Apple LLVM version 9.0.0 (clang-900.0.37)
Target: x86_64-apple-darwin16.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

**Comment by JustasMasiulis** [comment]
Merged. Thanks for the contribution :+1:

**Pull request merged**
